List<String> genre = [
  'Action',
  'Adventure',
  'Animation',
  'Anime',
  'Comedy',
  'Crime',
  'Documentary',
  'Family',
  'Fantasy',
  "Game Show",
  'Horror',
  'Lifestyle',
  'Music',
  'Musical',
  'Mystery',
  'Reality TV',
  'Romance',
  'Sci-Fi',
  'Seasonal',
  'Short',
  'Sport',
  'Thriller',
  'Western'
  //     "action".tr(),
  // "adventure".tr(),
  // "animation".tr(),
  // "biography".tr(),
  // "anime".tr(),
  // "comedy".tr(),
  // "crime".tr(),
  // "documentary".tr(),
  // "family".tr(),
  // "fantasy".tr(),
  // "game Show".tr(),
  // "horror".tr(),
  // "lifestyle".tr(),
  // "music".tr(),
  // "musical".tr(),
  // "mystery".tr(),
  // "reality_tV".tr(),
  // "romance".tr(),
  // "sci_fi".tr(),
  // "seasonal".tr(),
  // "short".tr(),
  // "sport".tr(),
  // "thriller".tr(),
  // "western".tr(),
];
